name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    name: Build
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libwebkit2gtk-4.1-dev

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build examples
        run: |
          go build ./examples/basic
          go build ./examples/uri-scheme

      - name: Run tests
        run: go test ./...
